apiVersion: v1
kind: Service
metadata:
  name: grafana-np
  namespace: monitoring
spec:
  selector:
    app: grafana
  ports:
  - protocol: "TCP"
    port: 3000
    targetPort: 3000
    nodePort: 30103
  type: NodePort
